permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

highlighter: rouge

markdown: kramdown

title : Feedback Hub Online 🏴‍☠️
tagline:
author :
  name : Rafael Rivera
  email :
  github : riverar
  twitter : WithinRafael
  feedburner :

production_url : https://feedbackhub.online

JB :
  version : 0.3.0

  BASE_PATH : false
  ASSET_PATH : false

  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : false

  analytics :
    provider : false

  sharing :
    provider : false
  
collections:
  announcements:
    output: true